spring.application.name=mypianolist
spring.datasource.url=jdbc:postgresql://localhost:5432/mypianolist
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.security.user.name=maxkemzi
spring.security.user.password=123456
spring.main.banner-mode=off
