spring.application.name=mypianolist
spring.datasource.url=jdbc:postgresql://localhost:5432/mypianolist
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.security.user.name=maxkemzi
spring.security.user.password=123456
spring.main.banner-mode=off
jwt.access-token.key=lujtTkJ8U2cHyVFunP1Mj2+EmkQG7IveF1/HpKOW2OQ=
jwt.refresh-token.key=Ax46SgFxobarXiFmiauIBZbf24ABZcsfkW9pNPWoCkA=

